/**
 * @file SHA1_vectors.h
 *
 * @copyright @parblock
 * Copyright (c) 2021 Semiconductor Components Industries, LLC (d/b/a
 * onsemi), All Rights Reserved
 *
 * This code is the property of onsemi and may not be redistributed
 * in any form without prior written permission from onsemi.
 * The terms of use and warranty for this code are covered by contractual
 * agreements between onsemi and the licensee.
 *
 * This is Reusable Code.
 * @endparblock
 */
#ifndef SHA1_VECTORS_H_
#define SHA1_VECTORS_H_

/* ----------------------------------------------------------------------------
 * If building with a C++ compiler, make all of the definitions in this header
 * have a C binding.
 * ------------------------------------------------------------------------- */
#ifdef __cplusplus
extern "C"
{
#endif    /* ifdef __cplusplus */

/*
 * Autogenerated Test Vectors - Do Not Edit
 */


#ifndef _SHA_STRUCTURE_DEFINED_
#define _SHA_STRUCTURE_DEFINED_

typedef struct {
    uint32_t            digestLength;
    uint32_t            messageLength;
    const uint8_t       *digest;
    const unsigned char *message;
} tSHAFields, *pSHAFields;

#endif /* _SHA_STRUCTURE_DEFINED_ */ 

/**
 * @brief Define the initial digest for sample 1
 */
static const uint8_t SHA1_1_DIGEST[] __attribute__((aligned(16))) = {
        0xA9, 0x99, 0x3E, 0x36, 0x47, 0x06, 0x81, 0x6A, 
        0xBA, 0x3E, 0x25, 0x71, 0x78, 0x50, 0xC2, 0x6C, 
        0x9C, 0xD0, 0xD8, 0x9D
    };

/**
 * @brief Define the fields structure for sample 1
 */
static const tSHAFields SHA1_1 = {
    .digestLength  = 20,
    .digest        = SHA1_1_DIGEST,
    .messageLength = 3,
    .message       = (const unsigned char *) "abc"
};

/**
 * @brief Define the initial digest for sample 2
 */
static const uint8_t SHA1_2_DIGEST[] __attribute__((aligned(16))) = {
        0x84, 0x98, 0x3E, 0x44, 0x1C, 0x3B, 0xD2, 0x6E, 
        0xBA, 0xAE, 0x4A, 0xA1, 0xF9, 0x51, 0x29, 0xE5, 
        0xE5, 0x46, 0x70, 0xF1
    };

/**
 * @brief Define the fields structure for sample 2
 */
static const tSHAFields SHA1_2 = {
    .digestLength  = 20,
    .digest        = SHA1_2_DIGEST,
    .messageLength = 56,
    .message       = (const unsigned char *) "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"
};



static const pSHAFields SHA1_TABLES[] = {
    (const pSHAFields) &SHA1_1,
    (const pSHAFields) &SHA1_2,
    (const pSHAFields) NULL
};

/* ----------------------------------------------------------------------------
 * Close the 'extern "C"' block
 * ------------------------------------------------------------------------- */
#ifdef __cplusplus
}
#endif    /* ifdef __cplusplus */

#endif /* SHA1_VECTORS_H_ */
