/**
 * @file SHA256_vectors.h
 *
 * @copyright @parblock
 * Copyright (c) 2021 Semiconductor Components Industries, LLC (d/b/a
 * onsemi), All Rights Reserved
 *
 * This code is the property of onsemi and may not be redistributed
 * in any form without prior written permission from onsemi.
 * The terms of use and warranty for this code are covered by contractual
 * agreements between onsemi and the licensee.
 *
 * This is Reusable Code.
 * @endparblock
 */
#ifndef SHA256_VECTORS_H_
#define SHA256_VECTORS_H_

/* ----------------------------------------------------------------------------
 * If building with a C++ compiler, make all of the definitions in this header
 * have a C binding.
 * ------------------------------------------------------------------------- */
#ifdef __cplusplus
extern "C"
{
#endif    /* ifdef __cplusplus */

/*
 * Autogenerated Test Vectors - Do Not Edit
 */


#ifndef _SHA_STRUCTURE_DEFINED_
#define _SHA_STRUCTURE_DEFINED_

typedef struct {
    uint32_t            digestLength;
    uint32_t            messageLength;
    const uint8_t       *digest;
    const unsigned char *message;
} tSHAFields, *pSHAFields;

#endif /* _SHA_STRUCTURE_DEFINED_ */ 

/**
 * @brief Define the initial digest for sample 1
 */
static const uint8_t SHA256_1_DIGEST[] __attribute__((aligned(16))) = {
        0xBA, 0x78, 0x16, 0xBF, 0x8F, 0x01, 0xCF, 0xEA, 
        0x41, 0x41, 0x40, 0xDE, 0x5D, 0xAE, 0x22, 0x23, 
        0xB0, 0x03, 0x61, 0xA3, 0x96, 0x17, 0x7A, 0x9C, 
        0xB4, 0x10, 0xFF, 0x61, 0xF2, 0x00, 0x15, 0xAD
    };

/**
 * @brief Define the fields structure for sample 1
 */
static const tSHAFields SHA256_1 = {
    .digestLength  = 32,
    .digest        = SHA256_1_DIGEST,
    .messageLength = 3,
    .message       = (const unsigned char *) "abc"
};

/**
 * @brief Define the initial digest for sample 2
 */
static const uint8_t SHA256_2_DIGEST[] __attribute__((aligned(16))) = {
        0x24, 0x8D, 0x6A, 0x61, 0xD2, 0x06, 0x38, 0xB8, 
        0xE5, 0xC0, 0x26, 0x93, 0x0C, 0x3E, 0x60, 0x39, 
        0xA3, 0x3C, 0xE4, 0x59, 0x64, 0xFF, 0x21, 0x67, 
        0xF6, 0xEC, 0xED, 0xD4, 0x19, 0xDB, 0x06, 0xC1
    };

/**
 * @brief Define the fields structure for sample 2
 */
static const tSHAFields SHA256_2 = {
    .digestLength  = 32,
    .digest        = SHA256_2_DIGEST,
    .messageLength = 56,
    .message       = (const unsigned char *) "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"
};



static const pSHAFields SHA256_TABLES[] = {
    (const pSHAFields) &SHA256_1,
    (const pSHAFields) &SHA256_2,
    (const pSHAFields) NULL
};

/* ----------------------------------------------------------------------------
 * Close the 'extern "C"' block
 * ------------------------------------------------------------------------- */
#ifdef __cplusplus
}
#endif    /* ifdef __cplusplus */

#endif /* SHA256_VECTORS_H_ */
